FROM node:21-alpine

WORKDIR /usr/src/app

COPY . .

RUN npm install

# Build the project
RUN npm run build

RUN npx prisma generate

# Check the build output
RUN ls -l /usr/src/app/dist

RUN rm -rf ./src

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
