services:
  nutric_api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      env_file: .env
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - nutric_db
      

  nutric_db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      env_file: .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
